---
- hosts: cp-mgmt-server
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{fingerprint}}"
    register: login_response
    tags: login
  - name: "add gateway w/ sic"
    check_point_mgmt:
      command: add-simple-gateway
      parameters:
        name: "{{gateway2}}"
        ipv4-address: "{{gateway2_address}}"
        firewall: "true"
        one-time-password: "{{sic}}"
        color: "olive"
        url-filtering: "true"   
        application-control: "true"
        version: "R80.10"
        anti-virus: "true"
        anti-bot: "true"
        ips: "true"
      session-data: "{{login_response}}"
  - name: "add Web Network Object"
    check_point_mgmt:
      command: add-network
      parameters:
        name: "Web-Network"
        subnet: "192.168.74.0"
        mask-length: "24"
        color: "olive"
        nat-settings:
          auto-rule: "true"
          method: "hide"
          hide-behind: "gateway"
          method: "hide"
      session-data: "{{login_response}}"
  - name: "add Web Server Object"
    check_point_mgmt:
      command: add-host
      parameters:
        name: "Simple-Web-Server"
        ip-address: "192.168.74.200"
        nat-settings:
          auto-rule: "true"
          method: "static"
          ip-address: "192.168.74.2"
        host-servers:
          web-server: "true"
          web-server-config:
            listen-standard-port: "true"
            operating-system: "x86 linux"
        color: "olive" 
      session-data: "{{login_response}}"
  - name: "add R80.10-GW-2 to CP-Gateways Group Object"
    check_point_mgmt:
      command: set-group
      parameters:
        name: "CP-Gateways"
        members:
          add: "R80.10-GW-2"
      session-data: "{{login_response}}"
  - name: "add Web-Network to Wild Access Rule"
    check_point_mgmt:
      command: set-access-rule
      parameters:
        layer: "Network"
        name: "Wild Access"
        source:
          add: "Web-Network"
      session-data: "{{login_response}}"
  - name: "add Allow Web Request Rule"
    check_point_mgmt:
      command: add-access-rule
      parameters:
        layer: "Network"
        position:
          above: "Stop External"
        name: "Allow Web Requests"
        action: "Accept"
        destination: "Simple-Web-Server"
        service:
          - "http"
          - "https"
        enabled: "true"
        track:
          type: "Log"
      session-data: "{{login_response}}"
  - name: "publish this session"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"
  - name: "install policy"
    check_point_mgmt:
      command: install-policy
      parameters:
        policy-package: "standard"
        targets: "R80.10-GW-2"
        threat-prevention: "false"
      session-data: "{{login_response}}"
  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"
    tags: logout
